import React from "react";
import HeroSection from "../components/Hero/HeroSection";
import Head from "next/head";

const LandingPage = () => {
  return (
    <div className='w-screen h-screen flex justify-center items-center'>
      <Head>
        <title>OrchidFriendZ</title>
        {/* Are these next two tags necessary? Idk */}
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeroSection
        heading='OrchidFriendZ'
        message="Let's grow some orchids n sheeit"
      />
    </div>
  );
};

export default LandingPage;
