import Head from 'next/head'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'

import Topnav from "../components/navigation/Topnav";
import HomePage from './Home'
import Account from '../components/Account'

const Home = () => {
  const session = useSession()
  const supabase = useSupabaseClient()

  return (
      <div className='w-[20rem]' style={{ padding: '50px 0 100px 0' }}>
        {!session ? (
            <Auth
                providers={
                [
                    'google',
                    'facebook'
                ]
                }
                supabaseClient={supabase}
                appearance={{ theme: ThemeSupa }}
                theme="dark"
            />
        ) : (
            <div>
                <Head>
                    <title>Orchid FriendZ</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="stylesheet"
                          href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"
                          referrerPolicy="no-referrer"/>
                </Head>

                <Topnav />
                <HomePage />
            </div>
        )}
      </div>
  )
}

export default Home